apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-processor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-processor
  template:
    metadata:
      labels:
        app: audio-processor
    spec:
      containers:
        - name: application
          # Your custom Azure Container Registry image
          image: araudioacpavlmarg123.azurecr.io/ar-audio-processor:v1
          ports:
            - containerPort: 8080
          env:
            # The network bridge to your new Kafka cluster
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: audio-processor
  namespace: default
spec:
  selector:
    app: audio-processor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080